version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}

  frontend:
    build: ./100729832_comp3133_assignment2
    container_name: frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend